# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33f6724cdd6220c1fd5f7ece62e1a3b6ad45ea4a17b5e823b8f5ef20459c97dc49877bb5d4e57f518b310a08fdeedfadacd4e1f11ff3a77522aa5f31fc4e79d2

test:
  secret_key_base: 53e62957a1cc8d0e64afb468a12780a9452fcc47c9c006ad60ec630c5466942fcd3f5415c45bbab8a77a303837ba392e9431b706c90a9f12b876cb6ebfbc4715

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
